[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts =
    -q
    --reuse-db
    --strict-markers
    --disable-warnings
asyncio_mode = auto
markers =
    slow: sekin ishlaydigan testlar
