# Generated by Django 4.2.14 on 2026-08-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('order_created', 'Yangi buyurtma'), ('order_accepted', 'Buyurtma qabul qilindi'), ('driver_arrived', 'Haydovchi yetib keldi'), ('order_started', 'Safar boshlandi'), ('order_completed', 'Safar yakunlandi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('payment_paid', "To'lov qabul qilindi"), ('system', 'Tizim xabari')], max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
