# Generated by Django 4.2.14 on 2026-08-06 07:53

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.avatar_upload_to, validators=[apps.common.uploads.validate_image_file], verbose_name='Avatar rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Avatar (tashqi havola)'),
        ),
    ]
