# Generated by Django 4.2.14 on 2026-08-03 17:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('driver_arrived', 'Haydovchi yetib keldi'), ('ongoing', "Yo'lda"), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=30)),
                ('from_address', models.CharField(max_length=255)),
                ('from_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('to_address', models.CharField(max_length=255)),
                ('to_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('click', 'Click'), ('payme', 'Payme')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Xato')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(blank=True, max_length=50)),
                ('base_fare', models.PositiveIntegerField(verbose_name="Boshlang'ich narx")),
                ('per_km', models.PositiveIntegerField(verbose_name='Km narxi')),
                ('per_minute', models.PositiveIntegerField(verbose_name='Daqiqa narxi')),
                ('minimum_fare', models.PositiveIntegerField(verbose_name='Minimal narx')),
                ('icon_url', models.URLField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'db_table': 'tariffs',
                'ordering': ['base_fare'],
            },
        ),
    ]
