# Generated by Django 4.2.14 on 2026-08-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_review_review_uniq_review_per_order_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
