# Generated by Django 4.2.14 on 2026-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyEquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('earth', 'Yer ishlari'), ('lift', "Ko'tarish"), ('road', "Yo'l"), ('loader', 'Yuklovchi')], max_length=20)),
                ('items', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('contacted', "Bog'lanildi"), ('confirmed', 'Tasdiqlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': "Og'ir texnika so'rovi",
                'verbose_name_plural': "Og'ir texnika so'rovlari",
                'db_table': 'heavy_equipment_requests',
            },
        ),
        migrations.CreateModel(
            name='WeddingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(max_length=100)),
                ('car_count', models.PositiveIntegerField(default=1)),
                ('decoration_type', models.CharField(blank=True, choices=[('flowers', 'Gullar'), ('balloons', 'Sharlar'), ('ribbons', 'Lentalar')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('contacted', "Bog'lanildi"), ('confirmed', 'Tasdiqlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': "To'y transporti so'rovi",
                'verbose_name_plural': "To'y transporti so'rovlari",
                'db_table': 'wedding_requests',
            },
        ),
    ]
