# Generated by Django 4.2.14 on 2026-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavyequipmentrequest',
            name='estimated_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxminiy narx'),
        ),
    ]
