# Generated by Django 4.2.14 on 2026-08-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0002_heavyequipmentrequest_estimated_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heavyequipmentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Og'ir texnika so'rovi", 'verbose_name_plural': "Og'ir texnika so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='weddingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "To'y transporti so'rovi", 'verbose_name_plural': "To'y transporti so'rovlari"},
        ),
        migrations.AddField(
            model_name='heavyequipmentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heavy_equipment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weddingrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
