# Generated by Django 4.2.14 on 2026-08-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0003_alter_heavyequipmentrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDriverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(max_length=100)),
                ('driver_experience', models.CharField(choices=[('1-3', '1-3 yil'), ('3-5', '3-5 yil'), ('5-10', '5-10 yil'), ('10+', '10 yildan ortiq')], max_length=10)),
                ('contract_duration', models.CharField(choices=[('1_day', '1 kun'), ('1_week', '1 hafta'), ('1_month', '1 oy'), ('3_months', '3 oy'), ('6_months', '6 oy'), ('1_year', '1 yil')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('contacted', "Bog'lanildi"), ('confirmed', 'Tasdiqlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_driver_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Shaxsiy haydovchi so'rovi",
                'verbose_name_plural': "Shaxsiy haydovchi so'rovlari",
                'db_table': 'personal_driver_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftMemorialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('gift', 'Hadiya'), ('memorial', 'Janoza / Maraka')], max_length=20)),
                ('decoration_type', models.CharField(blank=True, choices=[('flowers', 'Gullar'), ('balloons', 'Sharlar'), ('ribbons', 'Lentalar')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('contacted', "Bog'lanildi"), ('confirmed', 'Tasdiqlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_memorial_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hadiya/Maraka so'rovi",
                'verbose_name_plural': "Hadiya/Maraka so'rovlari",
                'db_table': 'gift_memorial_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('wedding', "To'y va tantana"), ('memorial', 'Maraka marosimi'), ('tour', 'Tur va sayohat')], max_length=20)),
                ('bus_brand', models.CharField(max_length=100)),
                ('bus_count', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('contacted', "Bog'lanildi"), ('confirmed', 'Tasdiqlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Avtobus so'rovi",
                'verbose_name_plural': "Avtobus so'rovlari",
                'db_table': 'bus_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
