# Generated by Django 4.2.14 on 2026-08-03 17:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Mashina modeli')),
                ('car_color', models.CharField(blank=True, max_length=50, verbose_name='Rangi')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='Davlat raqami')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Guvohnoma')),
                ('is_active', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_online', models.BooleanField(default=False, verbose_name='Onlayn')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Joylashuv')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Reyting')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Safarlar')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'db_table': 'drivers',
            },
        ),
    ]
