# Generated by Django 4.2.14 on 2026-08-06 07:53

import apps.common.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.car_photo_upload_to, validators=[apps.common.uploads.validate_image_file], verbose_name='Mashina rasmi'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.driver_doc_upload_to, validators=[apps.common.uploads.validate_image_file], verbose_name='Haydovchilik guvohnomasi'),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.driver_doc_upload_to, validators=[apps.common.uploads.validate_image_file], verbose_name='Pasport'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tech_passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.driver_doc_upload_to, validators=[apps.common.uploads.validate_image_file], verbose_name='Texnik pasport'),
        ),
    ]
